global:
  scrape_interval: 15s # How frequently to scrape targets by default.
  scrape_timeout: 10s # How long until a scrape request times out.
  evaluation_interval: 15s # How frequently to evaluate rules.

# A scrape configuration
scrape_configs:
  - job_name: aggregator
    scheme: http
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    follow_redirects: true
    static_configs:
    - targets: 
      - localhost:3000